### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by CueMaxX** [aindilis/free-life-planner#35]
Hi there,
after bringing up flp in virtualbox, it says "DONE LOADING FREE-LIFE-PLANNER", however, there is nothing available at port 3000. netstat -nlp does not show a process with open port @3000... Is there any way of troubleshooting what went wrong?

<img width="1114" alt="Screen Shot 2023-01-16 at 3 49 49 PM" src="https://user-images.githubusercontent.com/8759374/212740052-1902b0a2-1dd8-4665-ade2-f8e5b38d5672.png">
<img width="1114" alt="Screen Shot 2023-01-16 at 3 50 16 PM" src="https://user-images.githubusercontent.com/8759374/212740067-edf475e0-bc07-4aac-bf1a-d59220301fc2.png">

**Comment by aindilis** [comment]
Hi,

Please try running `sudo ifconfig enp0s3 10.0.2.15 up` , possibly replacing enp0s3 with whatever the default network device is.  Then please go to the bottom left window and C-c and re-run the `cd /var/lib/myfrdcsa/codebases/minor/fcms/FCMS && ./begin-fcms` command.

I had to enable the network by going to VirtualBox's menu and selecting Devices -> Network -> Connect Network Adapter , in order for it to load the FLP CDNs for FLP to start properly.  But this VM is out of date and may present a security risk.

I am in the process of finishing the Panoply installer script and when that is working, I will put out another version of the Panoply VM based on the most recent Debian stable, and probably using libvirt instead of Virtualbox. I am hoping to have this done in the next month. 

Please note that this version of FLP is barebones, it was written before the bulk of the features were added. It is still useful however.  

The current estimated time frame for the complete release of the current FLP is 01-01-2025.

Thanks,
aindilis
